### ISSUE TITLE
Issues running run_montecarlo.py and run_worst_case.py

### ISSUE THREAD

**Issue by flyforward2016** [nunobrum/PyLTSpice#129]
I was trying to run `run_montecarlo.py` and `run_worst_case.py` and they throw errors as below.  Could you shine some light on it? Thank you very much

`run_worst_case.py`
```
 PS C:\Users\nanka\Dropbox\PyLTSpice\examples> & C:/Anaconda3/envs/PyLTSpice/python.exe c:/Users/nanka/Dropbox/PyLTSpice/examples/run_worst_case.py
QSPICE not found in the usual locations. Please install it and try again.
Traceback (most recent call last):
  File "c:/Users/nanka/Dropbox/PyLTSpice/examples/run_worst_case.py", line 23, in <module>
    wca.run()  # Runs the simulation with splits of 100 runs each
TypeError: run() missing 1 required positional argument: 'netlist'
```

`run_montecarlo.py` 

```
Traceback (most recent call last):
  File "c:/Users/Documents/PyLTSpice/examples/run_montecarlo.py", line 25, in <module>
    logs = mc.read_logfiles()   # Reads the log files and stores the results in the results attribute
  File "C:\Users\miniconda3\envs\PyLTSpice\lib\site-packages\spicelib\sim\tookit\tolerance_deviations.py", line 243, in read_logfiles 
    raise RuntimeError("The analysis has not been executed yet")
RuntimeError: The analysis has not been executed yet
```

Here is the my configuration

Windows 10
Python 3.8
LTSpice 17.0.37.0
PyLTSpcie 5.2

**Comment by nunobrum** [comment]
Oh!  I've missed this notification and only seeing this issue now.  I hope you can excuse me this.
I've been moving much of the code from PyLTSpice to spicelib. Keeping PyLTSpice only for backwards compatibility and for simplifying things for users that don't want to use more than one simulator, relieving them from the burden of specifying the simulator.
The example you are using should have been updated in spicelib but not in PyLTSpice. 
The method that should be called is run_analysis() instead of just run()

**Comment by nunobrum** [comment]
I've just pushed a new version that fixes the problem you were facing.
The update on the PyPi repository will follow as soon as I also finish some fixes on the spicelib base repository.
