### ISSUE TITLE
Update old example

### ISSUE THREAD

**Issue by carlosdelfino** [nunobrum/PyLTSpice#141]
I'm trying to follow the example presented in this link article:
https://acidbourbon.wordpress.com/2019/11/26/seamless-integration-of-ltspice-in-python-numpy-signal-processing/

However, it seems to me that you are using an old version of PyLTSpice, is there any way to adapt this example to the most current version?

With this example, I get:

```/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/home/carlosdelfino/workspace/BasicaoDaEletronica/numpy_ltspice_filter/filter_demo.py", line 5, in <module>
    from apply_ltspice_filter import apply_ltspice_filter
  File "/home/carlosdelfino/workspace/BasicaoDaEletronica/numpy_ltspice_filter/apply_ltspice_filter.py", line 15, in <module>
    from PyLTSpice.LTSpice_RawRead import RawRead
ModuleNotFoundError: No module named 'PyLTSpice.LTSpice_RawRead'

```

Could anyone help me with this? Updating to the newest version?

Thanks.

**Comment by nunobrum** [comment]
Hello @carlosdelfino 

First question is whether PyLTspice is installed. 
If you lauch a python console and type `import PyLTSpice` does it generate the same error ?

If yes, you need to install PyLTSpice, but first you need to select the version that you want to install.

Basically there are two options for you. Either you can:
 - a)  install an older version of the PyLTSpice [2.3](https://pypi.org/project/PyLTSpice/2.3/) that is compatible with the code you are using, or...
 - b) Install the latest version of PyLTspice. In this case you might have to do some further work, 

I would advise the latter since it includes much more features and I think the transition can be made quite easily. I think you only need to rename some of the functions. Basically removing the LTSpice_ prefix.

I hope this sets you on the right track.

Good Luck and happy simulations,
Nuno
