### ISSUE TITLE
LookupError: unknown encoding: ansi in detect_encoding.py

### ISSUE THREAD

**Issue by helgelangen** [nunobrum/PyLTSpice#68]
Hello, thank you for this great piece of software.

While trying to load a manually modified SPICE netlist into SimCommander, I encountered the following error:
`File "/opt/homebrew/lib/python3.10/site-packages/PyLTSpice/detect_encoding.py", line 37, in detect_encoding
    with open(file_path, 'r', encoding=encoding) as f:
LookupError: unknown encoding: ansi`
The error being that there is no encoding named 'ansi' in Python 3 (there may have been in Python 2). I suggest simply removing 'ansi' from the list of encodings that are iterated over in detect_encoding.py. Also, shift-jis is misspelled (should be shift_jis). List of available encodings can be found here: https://docs.python.org/2/library/codecs.html#standard-encodings

(the reason I ran into this error, despite my netlist being utf-8 encoded, was that my file did not have a comment at the beginning of the file, which broke detect_encoding since it relies on finding a * at the beginning of the file to determine file encoding. I do not know if it is required to have a comment at the beginning of any SPICE netlist, however it is indeed required for SimCommander to be able to read it).

thanks,

**Comment by nunobrum** [comment]
Hello @helgelangen 

thanks for your input. I've made the changes on the encoding list as you recommended on the new branch that I've been working on. The no_ltspice_prefix where the need of prefixing all functions with LTSpice is no longer needed. 

On the need for the '*', indeed I'm expecting it on the beginning of the file.  This is the line 809 in SpiceEditor.py
`self.encoding = detect_encoding(netlist_file, '*')  # Normally the file will start with a '*'`

I've done so, because LTSpice does create netfiles starting with this character. I think this second parameter could be suppressed if you are using other sources.

Happy new Year,
Nuno
