### ISSUE TITLE
Interpretation / precision of time instances

### ISSUE THREAD

**Issue by patzf** [nunobrum/PyLTSpice#90]
Not sure if this is a precision issue but did a transient simulation with a duration of just a few microseconds. Extracted the result with

LTR = RawRead(filename_raw)
tTrc = LTR.get_trace('time')
t = 1e6*tTrc.get_wave()  #multiply by 1e6 to get time in us
UcTrc = LTR.get_trace('V(c)')
Uc = UcTrc.get_wave() # in V
print(t[0:50]) #print the values

When I look at the printed values of t, I see that there are wrong values (with negative sign) in there which causes the plotting going crazy =)
The print command above gives me e.g.

`
[ 0.          1.          1.0000022   1.0000066   1.0000154   1.00002634
  1.00004821  1.00009197  1.00017773  1.00031161  1.00053561  1.00059758
  1.00072151  1.00075214  1.00081341  1.00087747  1.001       1.00103676
  1.00108577  1.00118379  1.00137984  1.00173638  1.00220805  1.00267068
  1.00359595  1.00444282  1.00588001  1.00745261  1.00830441  1.00916114
  1.01001728  1.01094935  1.01233256  1.015099    1.02063186  1.03039749
  1.04016311  1.04992874  1.05969436  1.06945999  1.08899124  1.11828811
  1.14758499 -1.24035843  1.33313186 -1.53332718  1.73352249 -2.15832718
  2.58313186  3.001     ]
`

Maybe this is not even PyLTSpice related, but any idea what it going on here with the interpretation of the time values?

**Comment by nunobrum** [comment]
Hi there, 

this is a old very know issue that was discovered a long time ago. 
It's either LTspice or the struct library in Python is not unpacking float32 correctly. I personally bet on an LTspice issue.
The workaround is to use ``get_time_axis()`` instead of ``get_wave()`` and it should be fine. The latter just takes the absolute
value of the time, and the results are fine.

Best Regards,
Nuno
